faultTolerantResolve = (address, cb) ->
  opts =
    times: 2
    factor: 2
    minTimeout: 1 * 1000
    maxTimeout: 2 * 1000
    randomize: true

  operation = retry.operation(opts)
  operation.attempt (currentAttempt) ->
    dns.resolve address, (err, addresses) ->
      return  if operation.retry(err)
      cb operation.mainError(), operation.errors(), addresses
      return

    return

  return
dns = require("dns")
retry = require("../lib/retry")
faultTolerantResolve "nodejs.org", (err, errors, addresses) ->
  console.warn "err:"
  console.log err
  console.warn "addresses:"
  console.log addresses
  return

